package com.example.aslapp_backend.sevices;

import com.example.aslapp_backend.DTOs.requestDTOs.SignupDto;
import com.example.aslapp_backend.event.UserRegisteredEvent;
import com.example.aslapp_backend.models.Enum.ERole;
import com.example.aslapp_backend.models.Role;
import com.example.aslapp_backend.models.User;
import com.example.aslapp_backend.repositories.RoleRepository;
import com.example.aslapp_backend.repositories.UserRepository;
import jakarta.mail.MessagingException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.io.IOException;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AuthenticationServiceTest {

    @Mock
    private UserRepository userRepository;
    @Mock
    private PasswordEncoder passwordEncoder;
    @Mock
    private AuthenticationManager authenticationManager;
    @Mock
    private EmailService emailService;
    @Mock
    private JwtService jwtService;
    @Mock
    private ApplicationEventPublisher eventPublisher;
    @Mock
    private RoleRepository roleRepository;
    @Mock
    private UserService userService;

    @InjectMocks
    private AuthenticationService authenticationService;

    @Test
    void shouldRegisterUserSuccessfully() throws MessagingException, IOException {
        // Arrange
        SignupDto signupDto = new SignupDto("testuser", "password", "test@test.com", 25, "reason");
        User savedUser = new User("oussama", "encodedPass", "test@test.com", 25);
        savedUser.setId(1L);
        Role userRole = new Role(ERole.ROLE_USER);

        when(userRepository.existsByEmail(signupDto.getEmail())).thenReturn(false);
        when(passwordEncoder.encode(signupDto.getPassword())).thenReturn("encodedPass");
        when(roleRepository.existsByName(ERole.ROLE_ADMIN)).thenReturn(true);
        when(roleRepository.findByName(ERole.ROLE_USER)).thenReturn(Optional.of(userRole));
        when(jwtService.generateValidToken(any(User.class), any(), anyLong())).thenReturn("jwt-token");
        when(userService.saveUser(any(User.class))).thenReturn(savedUser);

        // Act
        User result = authenticationService.Signup(signupDto);

        // Assert
        assertNotNull(result);
        assertEquals("oussama", result.getUsername());
        verify(userService).saveUser(any(User.class));
        verify(eventPublisher).publishEvent(any(UserRegisteredEvent.class));
    }

    @Test
    void shouldLoginSuccessfully() throws MessagingException, IOException {
        // Arrange
        String email = "test@test.com";
        String password = "password";
        User user = new User("testuser", "encodedPass", email, 25);
        user.setEnabled(true);

        when(userRepository.findByEmail(email)).thenReturn(Optional.of(user));
        when(passwordEncoder.matches(password, user.getPassword())).thenReturn(true);

        // Act
        // Login() returns the authenticated User (JWT is generated by the controller layer)
        User result = authenticationService.Login(email, password);

        // Assert
        assertNotNull(result);
        assertEquals(email, result.getEmail());
        verify(authenticationManager).authenticate(any());
    }

    @Test
    void shouldValidateUser() {
        // Arrange
        String token = "jwt-token";
        String email = "test@test.com";
        User user = new User("testuser", "pass", email, 20);

        // valityUser() calls jwtService.extractUsername then userRepository.findByEmail
        when(jwtService.extractUsername(token)).thenReturn(email);
        when(userRepository.findByEmail(email)).thenReturn(Optional.of(user));
        when(jwtService.isTokenValid(token, user)).thenReturn(true);

        // Act
        boolean result = authenticationService.valityUser(token);

        // Assert
        assertTrue(result);
        assertTrue(user.getEnabled());
        verify(userRepository).save(user);
    }
}