spring.application.name=ASLapp_backend
server.port=8081
# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ASLapp
spring.datasource.username=postgres
spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Ensure Hibernate auto-generates tables
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ensure UTF-8 encoding is enforced
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
# JWT secret key
security.jwt.secret-key =oussama
security.jwt.expiration-time=2678400000

# application.properties
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.max-http-header-size=16384

# Mail properties
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=889916002@smtp-brevo.com
# oussama.abcde200@gmail.com
spring.mail.password=NcZvjhSqHz3XyrCG
  #xsmtpsib-8c5316acc29b97c50bb97448380ca7313df1703bb278fe656d56fe43f8a5c92b-caQkWR3TnxpM42sG
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.config.import=optional:file:.env[.properties]

#spring.cloud.azure.storage.blob.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
#spring.cloud.azure.storage.blob.endpoint=${AZURE_STORAGE_ACCOUNT_ENDPOINT}

# Disable AWS S3 for local development
spring.cloud.aws.s3.enabled=false
spring.cloud.aws.region.auto=false

# Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha


#spring.data.redis.password=
spring.data.redis.host=localhost
spring.data.redis.port=32768