spring.application.name=ASLapp_backend
# Database configuration
spring.datasource.url=jdbc:mysql://localhost:5432/ASLAPP
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key
security.jwt.secret-key ="oussama"
security.jwt.expiration-time=2678400000
#
# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.config.import=optional:file:.env[.properties]